version: "3.8"

services:
  flask-api:
    build:
      context: ./flask_api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./flask_api:/app

  nodejs-api:
    build:
      context: ./node_api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node_api:/app
      - /app/node_modules
    env_file:
      - ./node_api/config.env
    depends_on:
      - flask-api
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
